## Finding positional maximum and minimum

In [2]:

import tensorflow as tf 


In [4]:

# Creating a random tensor to find its positional maximum and minimum 

F = tf.random.uniform(shape = [50])

F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.882251  , 0.61000276, 0.8397982 , 0.5120745 , 0.46924102,
       0.79902613, 0.8731812 , 0.09201634, 0.35981095, 0.41347384,
       0.8511441 , 0.1114521 , 0.08448577, 0.4959252 , 0.17486095,
       0.46399856, 0.72555065, 0.75357735, 0.96474004, 0.01571906,
       0.24592948, 0.33048368, 0.11296844, 0.7696165 , 0.24774325,
       0.18519688, 0.9691967 , 0.90434706, 0.66431105, 0.04224312,
       0.51676965, 0.5661807 , 0.03556287, 0.61319935, 0.6444652 ,
       0.7439474 , 0.22479272, 0.21055233, 0.73312354, 0.17941272,
       0.45505226, 0.78782356, 0.08053803, 0.66451895, 0.7171974 ,
       0.6374451 , 0.54298747, 0.35707426, 0.46476662, 0.08424962],
      dtype=float32)>

In [6]:

# finding the positional maximum 

tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=26>

In [8]:

# max value vako index hereko 

F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9691967>

In [9]:

# maximum value in tensor abs

tf.reduce_max(F)


<tf.Tensor: shape=(), dtype=float32, numpy=0.9691967>

In [11]:

# answer thik aayo ki nai vanera check gareko

F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [12]:

# finding the positional minimum

tf.argmin(F)


<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [13]:

F[tf.argmin(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.015719056>