In [2]:

# Import TensorFlow
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.10.0


In [4]:

numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

## --> NumPy arrays are primarily focused on numerical computations and provide a versatile way to represent and manipulate multi-dimensional arrays in Python. 

## --> TensorFlow tensors, on the other hand, extend the concept of arrays by incorporating a computation graph, allowing for deferred execution and enabling automatic differentiation, making it particularly suitable for building and training machine learning models.