
# Tensors and numpy 


We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:

    np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).
    tensor.numpy() - call on a tensor to convert to an ndarray.

Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.


In [1]:

import tensorflow as tf 

tf.__version__


2023-08-14 17:44:21.104813: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


'2.10.0'

In [3]:

# creating a tensor directly from numpy array

import numpy as np

A = tf.constant(np.array([3. , 7. , 11. ]))

A


2023-08-14 17:47:04.054542: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-14 17:47:04.446139: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 11.])>

In [4]:

# coverting the tensors into numpy array 

np.array(A) , type(np.array(A))

(array([ 3.,  7., 11.]), numpy.ndarray)

In [5]:

# converting our tensor A into numpy array

A.numpy() , type(A.numpy())

(array([ 3.,  7., 11.]), numpy.ndarray)

In [6]:

# Create a tensor from NumPy and from an array

numpy_A = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)

tensor_A = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)

numpy_A.dtype, tensor_A.dtype
     

(tf.float64, tf.float32)