# Creating random tensors

## --> Random tensors are of arbitary size ,which contain random numbers


In [4]:

# Importing TensorFlow

import tensorflow as tf

print(tf.__version__) 

2.10.0


In [5]:

# Creating two random (but the same ) tensors 

# Creating two random (but the same) tensors
random_gen = tf.random.Generator.from_seed(42)

random_1 = random_gen.normal(shape=(3, 2))  # Generate tensor from a normal distribution

random_gen = tf.random.Generator.from_seed(42)

random_2 = random_gen.normal(shape=(3, 2))

random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# tf.random.Generator.from_seed(42)
## -->  tf.random.Generator.from_seed(42) creates a random tensor is one way to ensure that you get the same sequence of random numbers each time you run your code.

# -->yesle random number generator instance create garxa,jasle kunai specific sequence (determined by seed value) follow garera numbers generate garxa



In [7]:

#  Creating a roandom tensor using tf.random.normal

normal_random_tensor = tf.random.normal(
                                            (4,3),
                                            mean=0.0,
                                            stddev=1.0,
                                            dtype=tf.dtypes.float32,
                                            seed=None,
                                            name=None
                                     )
normal_random_tensor




<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-2.2592185 , -1.0228261 , -0.22953701],
       [ 0.74923396,  1.7385935 ,  0.77194357],
       [ 1.3070687 ,  0.12780498, -0.95390934],
       [-0.8314998 , -0.6426141 , -0.6268184 ]], dtype=float32)>

In [8]:

# Generate a random tensor following a Poisson distribution
poisson_random_tensor = tf.random.poisson(
                                                shape=(4, 4),
                                                lam=3.0,
                                                dtype=tf.dtypes.float32,
                                                seed=None,
                                                name=None
                                            )

poisson_random_tensor


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[7., 1., 5., 6.],
       [7., 1., 1., 4.],
       [3., 2., 1., 4.],
       [1., 2., 0., 4.]], dtype=float32)>

In [9]:
# Generate a random tensor following a uniform distribution within a specified range
uniform_random_tensor = tf.random.uniform(
                                            shape=(3, 3),          # Shape of the tensor: 3 rows, 3 columns
                                            minval=0,              # Minimum value of the uniform distribution
                                            maxval=10,             # Maximum value of the uniform distribution
                                            dtype=tf.dtypes.int32,  # Data type of the tensor elements
                                            seed=None,             # Seed for reproducibility (optional)
                                            name=None              # Optional name for the operation
                                        )

uniform_random_tensor


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 6, 6],
       [6, 9, 5],
       [0, 6, 3]], dtype=int32)>