# Creating random tensors

## --> Random tensors are of arbitary size ,which contain random numbers


In [1]:

# Importing TensorFlow

import tensorflow as tf

print(tf.__version__) 

2023-08-04 11:56:40.376131: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.10.0


In [6]:

# Creating two random (but the same ) tensors 

# Creating two random (but the same) tensors
random_gen = tf.random.Generator.from_seed(42)

random_1 = random_gen.normal(shape=(3, 2))  # Generate tensor from a normal distribution

# random_gen = tf.random.Generator.from_seed(42)

random_2 = random_gen.normal(shape=(3, 2))

random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# tf.random.Generator.from_seed(42)
## -->  tf.random.Generator.from_seed(42) creates a random tensor is one way to ensure that you get the same sequence of random numbers each time you run your code.

# -->yesle random number generator instance create garxa,jasle kunai specific sequence (determined by seed value) follow garera numbers generate garxa

