# Expanding tensors :-

In [6]:

import tensorflow as tf
print(tf.__version__)


2.10.0


In [7]:

# Creating a rank 2 (dui ota dimension bhako ) tensor 

rank_2_tensor = tf.constant([ [4,7],
                              [5,8]
                            ])
rank_2_tensor 


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 7],
       [5, 8]], dtype=int32)>

In [3]:

# rank_2_tensor maa extra dimension thapdai

rank_3_tensor = rank_2_tensor[... , tf.newaxis]

rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[4],
        [7]],

       [[5],
        [8]]], dtype=int32)>

# Another way to expand tensor

## --> using tf.expand_dims method:-

In [4]:

tf.expand_dims(rank_2_tensor , axis = -1)

# -1 vaneko last axis expand gareko

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[4],
        [7]],

       [[5],
        [8]]], dtype=int32)>

In [5]:

tf.expand_dims(rank_2_tensor , axis = 0)

# suru maa (0th index maa) extra dimension add garxa


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[4, 7],
        [5, 8]]], dtype=int32)>