
# Matrix mutliplication

###  ---> One of the most common operations in machine learning algorithms is matrix multiplication.



## TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.



## The main two rules for matrix multiplication to remember are:

###    The inner dimensions must match:

### --->    (3, 5) @ (3, 5) won't work
### --->   (5, 3) @ (3, 5) will work
### --->    (3, 5) @ (5, 3) will work

##     The resulting matrix has the shape of the outer dimensions:

### --->    (5, 3) @ (3, 5) -> (5, 5)
### --->    (3, 5) @ (5, 3) -> (3, 3)

##    🔑 Note: '@' in Python is the symbol for matrix multiplication.



In [3]:

import tensorflow as tf 

print(tf.__version__)

2.10.0


In [5]:

tensor = tf.constant([
                      [10, 7],
                      [3, 4]
                     ])

tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [6]:

tf.matmul(tensor, tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [7]:

# matrix multuplication with python operator " @ "

tensor @ tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [8]:

# Creating a  (3, 2) tensor

X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])


# Creating another (3, 2) tensor

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [10]:

# Try to matrix multiply them (will error)

# X @ Y
     

In [14]:

# matrix multiplication garnalai kita  X ko waa ki Y ko shape change garna parxa 

# duitai tensor ko shape ( 3 * 2 ) ko form maa xa so kunai tensor lai ( 2 * 3 ) ko form maa change gare paxi matrai matrix multiplication possuble xa

# so reshaping the tensor X  using tf.reshape function 

reshaped_X = tf.reshape( X , shape = (2 ,3))

reshaped_X 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:

reshaped_X @ Y


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [16]:

tf.matmul(reshaped_X ,Y )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [18]:

# reshape ko satta transpose pani garna abs 

X , reshaped_X ,tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)