
# Matrix mutliplication

###  ---> One of the most common operations in machine learning algorithms is matrix multiplication.



## TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.



## The main two rules for matrix multiplication to remember are:

###    The inner dimensions must match:

### --->    (3, 5) @ (3, 5) won't work
### --->   (5, 3) @ (3, 5) will work
### --->    (3, 5) @ (5, 3) will work

##     The resulting matrix has the shape of the outer dimensions:

### --->    (5, 3) @ (3, 5) -> (5, 5)
### --->    (3, 5) @ (5, 3) -> (3, 3)

##    🔑 Note: '@' in Python is the symbol for matrix multiplication.



In [15]:

import tensorflow as tf 

print(tf.__version__)

2.10.0


In [16]:

tensor = tf.constant([
                      [10, 7],
                      [3, 4]
                     ])

tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [3]:

tf.matmul(tensor, tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [4]:

# matrix multuplication with python operator " @ "

tensor @ tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [5]:

# Creating a  (3, 2) tensor

X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])


# Creating another (3, 2) tensor

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [6]:

# Try to matrix multiply them (will error)

# X @ Y
     

In [7]:

# matrix multiplication garnalai kita  X ko waa ki Y ko shape change garna parxa 

# duitai tensor ko shape ( 3 * 2 ) ko form maa xa so kunai tensor lai ( 2 * 3 ) ko form maa change gare paxi matrai matrix multiplication possuble xa

# so reshaping the tensor X  using tf.reshape function 

reshaped_X = tf.reshape( X , shape = (2 ,3))

reshaped_X 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [8]:

reshaped_X @ Y


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [9]:

tf.matmul(reshaped_X ,Y )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [10]:

# reshape ko satta transpose pani garna abs 

X , reshaped_X ,tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

# The dot product

 ## ---> Multiplying matrices by eachother is also referred to as the dot product.

## ---> We can perform the tf.matmul() operation using tf.tensordot().

# tf.tensordot() function

## Syntax :- 
## ---> tf.tensordot(a, b, axes, name=None )


In [11]:

# performing dot product on X and Y  (X ra Y madhye kunai euta reshape/transpose garna parxa )

tf.tensordot(tf.transpose(X) ,Y , axes =1 )


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [12]:

# performing matrix multiplication on X and Y(transposed)

tf.matmul(X , tf.transpose(Y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [13]:

# performing matrix multiplication on X and Y( reshaped ) 

tf.matmul(X , tf.reshape(Y , shape = (2,3) ))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [14]:

# Check values of Y, reshape Y and tranposed Y

print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))
     

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)




As we can see, the outputs of tf.reshape() and tf.transpose() when called on Y, even though they have the same shape, are different.

This can be explained by the default behaviour of each method:

    tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
    
    tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.

So which should you use?

--> Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).

---> But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.
