# Indexing :-

In [2]:

import tensorflow as tf

print(tf.__version__)

2.10.0


# 1) 1D tensor (vector)

In [5]:

# Creating a 1D tensor (vector)

tensor_1d = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

tensor_1d


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [7]:

# Indexing
element = tensor_1d[3]  # Accesses the fourth element (index 3)

# Slicing
sub_tensor = tensor_1d[2:6]  # Extracts elements from index 2 to 5

element,sub_tensor


(<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6], dtype=int32)>)

# 2) 2D tensor (matrix)

In [9]:

# Creating a 2D tensor (matrix)

tensor_2d = tf.constant([ [1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]
                       ])

tensor_2d


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [10]:

# Indexing
element = tensor_2d[1, 2]  # Accesses element at row 1, column 2 (6)

# Slicing
row_slice = tensor_2d[0, :]   # first row extract garxa

column_slice = tensor_2d[:, 1]  # second column extract garxa

sub_tensor = tensor_2d[1:3, 0:2]  # row 1 ra 2 vako ani column 0 ra 1 vako euta subtensor extract garxa

element , row_slice , column_slice , sub_tensor


(<tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 8], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [7, 8]], dtype=int32)>)

# 3) 3D tensor :-

In [11]:

# Creating a 3D tensor

tensor_3d = tf.constant([
                          [[1, 2, 3],
                          [4, 5, 6]],
                          [[7, 8, 9],
                          [10, 11, 12]]
                        ])
tensor_3d


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [13]:


# Indexing
element_2 = tensor_3d[1, 0, 2]  # Accesses element at index (1, 0, 2)

# Slicing
sub_tensor_2 = tensor_3d[:, 1:2, 0]  # Extracts sub-tensor along the first axis, rows 1 to 2, column 0

element_2 , sub_tensor_2


(<tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[ 4],
        [10]], dtype=int32)>)

# 4) 4D Tensor:-

In [14]:

# Creating a 4D tensor
tensor_4d = tf.constant([
                           [[[1, 2],
                           [3, 4]], 
                           [[5, 6],
                           [7, 8]]], 
                           [[[9, 10], 
                           [11, 12]],
                           [[13, 14], 
                           [15, 16]]]
                        ])

# Indexing
element_4d = tensor_4d[1, 0, 1, 1]  # Accesses element at index (1, 0, 1, 1)

# Slicing
sub_tensor_4d = tensor_4d[0:2, :, 1, 0:2]  # Extracts sub-tensor along first axis, all rows, column 1, columns 0 to 1

tensor_4d ,element_4d , sub_tensor_4d


(<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 3,  4],
         [ 7,  8]],
 
        [[11, 12],
         [15, 16]]], dtype=int32)>)

# 5) 5D tensor :-

In [15]:

# Creating a 5D tensor

tensor_5d = tf.constant([
                           [[[ [1, 2] , [3, 4]] , [[5, 6] , [7, 8] ]],
                           [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]],
                          [[[[17, 18], [19, 20]], [[21, 22], [23, 24]]],
                           [[[25, 26], [27, 28]], [[29, 30], [31, 32]]]]
                         ])

# Indexing
element_5d = tensor_5d[1, 0, 1, 1, 0]  # Accesses element at index (1, 0, 1, 1, 0)

# Slicing
sub_tensor_5d = tensor_5d[:, 0:2, 1, 0, :]  # Extracts sub-tensor along first axis, rows 0 to 1, column 1, all along the last axis

tensor_5d , element_5d , sub_tensor_5d

(<tf.Tensor: shape=(2, 2, 2, 2, 2), dtype=int32, numpy=
 array([[[[[ 1,  2],
           [ 3,  4]],
 
          [[ 5,  6],
           [ 7,  8]]],
 
 
         [[[ 9, 10],
           [11, 12]],
 
          [[13, 14],
           [15, 16]]]],
 
 
 
        [[[[17, 18],
           [19, 20]],
 
          [[21, 22],
           [23, 24]]],
 
 
         [[[25, 26],
           [27, 28]],
 
          [[29, 30],
           [31, 32]]]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=23>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 5,  6],
         [13, 14]],
 
        [[21, 22],
         [29, 30]]], dtype=int32)>)