# Changing datatype of a tensor

In [3]:

import tensorflow as tf

tf.__version__


'2.10.0'

In [9]:

# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])

B, C


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [11]:

# Changing from float32 to float16 (reduced precision vaninxa)

D = tf.cast(B , dtype= tf.float16)

D,D.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [15]:

E = tf.cast(C , dtype= tf.float32)

E,E.dtype


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>,
 tf.float32)

In [16]:


E = tf.cast(C , dtype= tf.float16)

E,E.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>,
 tf.float16)