# Indexing Tensors :

## ---> Python list indexing jastai hunxa

In [9]:

import tensorflow as tf

print(tf.__version__)

2.10.0


In [10]:
# creating a rank 4 (4 dimension bhako) tensor

rank_4_tensor = tf.zeros(shape =(2,3,4,5))

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [11]:

# each dimension ko first 2 elements nikaleko

rank_4_tensor[:2, :2 , :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [12]:

# list banayera tesko first two elements access gareko

some_list =[1,2,3,4]
some_list[:2]


[1, 2]

In [13]:

# Getting the first element from each dimension from each index except for the final one

rank_4_tensor[:1, :1, :1, :]
     


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [14]:

rank_4_tensor[:1, :1, :, :1]
     

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [15]:

# Creating a rank 2 (dui ota dimension bhako ) tensor 

rank_2_tensor = tf.constant([ [4,7],
                              [5,8]
                            ])
rank_2_tensor , rank_2_tensor.ndim , rank_2_tensor.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 7],
        [5, 8]], dtype=int32)>,
 2,
 TensorShape([2, 2]))

In [19]:

# Getting last element of our python list and getting its last element 

some_list ,some_list[-1]

([1, 2, 3, 4], 4)

In [21]:

# rank_2_tensor ko each row ko last element nikeleko

rank_2_tensor , rank_2_tensor[ : , -1 ]


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 7],
        [5, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 8], dtype=int32)>)

In [23]:

# rank_2_tensor maa extra dimension thapdai

rank_3_tensor = rank_2_tensor[... , tf.newaxis]

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[4],
        [7]],

       [[5],
        [8]]], dtype=int32)>