In [4]:

# Importing TensorFlow

import tensorflow as tf

print(tf.__version__) 



2.10.0


In [5]:

# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [3]:


# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, random_1 == random_3, random_3 == random_4
     


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

## Shuffling the order of elements of a tensor :-

In [7]:
not_shuffled = tf.constant([
                                [10, 7],
                                [3, 4],
                                [2, 5]
                           ])

not_shuffled.ndim

2

In [8]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [12]:
# Shufflling our non-shuffled abs

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [18]:

# Shuffle in the same order every time using the seed parameter (won't acutally be the same)

tf.random.shuffle(not_shuffled, seed=42) # 

# Yo garda shuffle ta hunxa tara lagatar 2 choti eutai order hunxa ani arko choti balla order change hunxa


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

 # Random Seed Explanation: When we do things in a random way, like shuffling or generating random numbers, we often use something called a "random seed" to start the randomness. This seed helps us make sure that even though we're doing things randomly, we can repeat the randomness later if needed.

 ## --> This randomness actually comes from two seeds. One is like a big global seed that affects everything, and the other is like a smaller seed for a specific thing we're doing (like shuffling images).

 ## Setting the Global Seed: We can decide to set a global seed that affects everything we do that's random.

## How Seeds Work Together:

## No Seeds Set: If we don't set any seeds, the computer will pick a random one for us each time.

## Global Seed Set: If we only set the big global seed, the computer will use it to make sure our random things are kind of predictable but still different.
 
 ## Operation Seed Set: If we only set the smaller seed for a specific thing, the computer will use a default global seed along with it to decide the randomness.

## Both Seeds Set: If we set both the big global seed and the smaller seed, the computer will mix them together to decide how random things should be.

In [19]:

# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)
     

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>